# Numerical Computing with Python and Numpy

![](https://i.imgur.com/mg8O3kd.png)

### Part 6 of "Data Analysis with Python: Zero to Pandas"


This tutorial series is a beginner-friendly introduction to programming and data analysis using the Python programming language. These tutorials take a practical and coding-focused approach. The best way to learn the material is to execute the code and experiment with it yourself. Check out the full series here:

1. [First Steps with Python and Jupyter](https://jovian.ai/aakashns/first-steps-with-python)
2. [A Quick Tour of Variables and Data Types](https://jovian.ai/aakashns/python-variables-and-data-types)
3. [Branching using Conditional Statements and Loops](https://jovian.ai/aakashns/python-branching-and-loops)
4. [Writing Reusable Code Using Functions](https://jovian.ai/aakashns/python-functions-and-scope)
5. [Reading from and Writing to Files](https://jovian.ai/aakashns/python-os-and-filesystem)
6. [Numerical Computing with Python and Numpy](https://jovian.ai/aakashns/python-numerical-computing-with-numpy)
7. [Analyzing Tabular Data using Pandas](https://jovian.ai/aakashns/python-pandas-data-analysis)
8. [Data Visualization using Matplotlib & Seaborn](https://jovian.ai/aakashns/python-matplotlib-data-visualization)
9. [Exploratory Data Analysis - A Case Study](https://jovian.ai/aakashns/python-eda-stackoverflow-survey)

In [2]:
# Based on some statical analysis of historical data, we might come up with reasonable values for the weights w1, w2, and w3. Here's an example set of values:

w1, w2, w3 = 0.3, 0.2, 0.5

In [3]:
# To begin, we can define some variables to record climate data for a region.

kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [4]:
# We can now substitute these variables into the linear equation to predict the yield of apples.

kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [5]:
# To make it slightly easier to perform the above computation for multiple regions, 
# we can represent the climate data for each region as a vector, i.e., a list of numbers.

kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [6]:
weights = [w1, w2, w3]

def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [7]:
crop_yield(kanto, weights)

56.8

In [8]:
crop_yield(johto, weights)

76.9

In [9]:
crop_yield(unova, weights)

74.9

In [10]:
!pip install numpy --upgrade --quiet

In [11]:
import numpy as np

In [12]:
kanto = np.array([73, 67, 43])

kanto

array([73, 67, 43])

In [13]:
weights = np.array([w1, w2, w3])

weights

array([0.3, 0.2, 0.5])

In [14]:
# Operating on Numpy arrays

np.dot(kanto, weights)

56.8

In [15]:
(kanto * weights).sum()

56.8

In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr1 * arr2

array([ 4, 10, 18])

In [17]:
arr2.sum()

15

In [18]:
# Python lists
arr1 = list(range(1000))
arr2 = list(range(1000, 2000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [19]:
%%time
result = 0
for x1, x2, in zip(arr1, arr2):
  result += x1*x2

result

CPU times: total: 0 ns
Wall time: 0 ns


832333500

In [20]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 945 µs


832333500

In [21]:
# Multi-dimensional Numpy arrays

climate_data = np.array([
  [73, 67, 43],
  [91, 88, 64],
  [87, 134, 58],
  [102, 43, 37],
  [69, 96, 70]])

climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [22]:
# 2D array (matrix)

climate_data.shape

(5, 3)

In [23]:
weights

array([0.3, 0.2, 0.5])

In [24]:
# 1D array (vector)

weights.shape

(3,)

In [25]:
# 3D array
arr3 = np.array([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.5]]])

arr3.shape

(2, 2, 3)

In [26]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [27]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [28]:
## Working with CSV data files

import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x205d1f034c0>)

In [29]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [30]:
climate_data.shape

(10000, 3)

In [31]:
weights = np.array([0.3, 0.2, 0.5])
yields = climate_data @ weights
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [32]:
yields.shape

(10000,)

In [33]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [34]:
np.savetxt('climate_results.txt',
           climate_results,
           fmt='%.2f',
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples',
           comments='')

In [35]:
# Arithmetic operations, broadcasting and comparison

arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

arr3 = np.array([[11, 12, 13, 14],
                 [15, 16, 17, 18],
                 [19, 11, 12, 13]])

# Adding a scalar

arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [36]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [37]:
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [38]:
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [39]:
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [40]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

arr2.shape

(3, 4)

In [41]:
arr4 = np.array([4, 5, 6, 7])

arr4.shape

(4,)

In [42]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [43]:
arr5 = np.array([7, 8])

arr5.shape

(2,)

In [44]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [45]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [46]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [47]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [48]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [49]:
(arr1 == arr2).sum()

3

In [50]:
arr3 = np.array([
    [[11, 12, 13, 14],
     [13, 14, 15, 19]],

    [[15, 16, 17, 21],
     [63, 92, 36, 18]],

    [[98, 32, 81, 23],
     [17, 18, 19.5, 43]]])

arr3.shape

(3, 2, 4)

In [51]:
# Single element
arr3[1, 1, 2]

36.0

In [52]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [53]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [54]:
# Mixing indices and ranges
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [55]:
# Using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [56]:
# Using fewer indices
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [57]:
# Using too many indices
arr3[1, 3, 2, 1]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed